#! /bin/sh
sxhkd &
wmname LG3D &

# 
# Monitor
# 

edp=0x00200002
hdmi=0x00200004

## When didn't find additional monitor, its rule ignore.
bspc monitor $edp -d terminal browser editor slack media other
bspc monitor $hdmi -d browser slack other


#
# Window rule
# 

bspc rule -a Firefox desktop='browser'

bspc rule -a Sublime_text desktop='editor'
bspc rule -a AndroidStudio desktop='editor'
bspc rule -a jetbrains-clion desktop='editor'
bspc rule -a jetbrains-goland desktop='editor'
bspc rule -a jetbrains-pycharm desktop='editor'
bspc rule -a jetbrains-rider desktop='editor'
bspc rule -a jetbrains-toolbox desktop='editor' state=floating

bspc rule -a Slack desktop='slack'
bspc rule -a Gimp desktop='media' state=floating follow=on 

bspc rule -a rofi state=floating follow=on


#
# Startup
#

amixer set Master mute &
amixer set Capture mute &
sh ~/.screenlayout/swk.sh &
sh ~/.config/script/polybar.sh &
compton -b --config .config/compton/compton.conf &
sh ~/.config/script/feh.sh &
nm-applet &
fcitx &
jetbrains-toolbox &

# sakura &
# firefox &
# subl &
slack &


# 
# Focus Behavior
#

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config swallow_first_click     true


#
# Pointer Action
#

bspc config pointer_modifier mod4
bspc config pointer_motion_interval 50
bspc config pointer_action1 resize_side
bspc config pointer_action2 none
bspc config pointer_action3 move

#
# Appearance
#

bspc config window_gap  10
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle    true

# Border
bspc config border_width         4
bspc config normal_border_color  '#555555'
bspc config active_border_color  '#555555'
bspc config focused_border_color '#4dd0e1'
